name: fastqc
description: Run FastQC on sequenced reads
keywords:
  - quality control
  - qc
  - adapters
  - fastq
tools:
  - fastqc:
      description: |
        FastQC gives general quality metrics about your reads.
        It provides information about the quality score distribution
        across your reads, the per base sequence content (%A/C/G/T).

        You get information about adapter contamination and other
        overrepresented sequences.
      homepage: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
      documentation: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/
      licence: ["GPL-2.0-only"]
      identifier: biotools:fastqc
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies: []
output:
  html:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.html":
          type: file
          description: FastQC report
          pattern: "*_{fastqc.html}"
          ontologies: []
  zip:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.zip":
          type: file
          description: FastQC report archive
          pattern: "*_{fastqc.zip}"
          ontologies: []
  versions_fastqc:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - fastqc:
          type: string
          description: The tool name
      - fastqc --version | sed "/FastQC v/!d; s/.*v//":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - fastqc:
          type: string
          description: The tool name
      - fastqc --version | sed "/FastQC v/!d; s/.*v//":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@drpatelh"
  - "@grst"
  - "@ewels"
  - "@FelixKrueger"
maintainers:
  - "@drpatelh"
  - "@grst"
  - "@ewels"
  - "@FelixKrueger"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/fastqc:0.12.1--e455e32f745abe68
      build_id: bd-e455e32f745abe68_1
      scan_id: sc-f102f736465af88c_1
    linux/amd64:
      name: community.wave.seqera.io/library/fastqc:0.12.1--5cb1a2fa2f18c7c2
      build_id: bd-5cb1a2fa2f18c7c2_1
      scan_id: sc-0c0466326b6b77d2_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/fastqc:0.12.1--5c4bd442468d75dd
      build_id: bd-5c4bd442468d75dd_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/f2/f20b021476d1d87658820f971ebecc1e8cdbde0f338eb0d9cea2b0a8fc54a54b/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/fastqc:0.12.1--127a87fc06499035
      build_id: bd-127a87fc06499035_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/46/46daf2dad0169afd2ae047c3e50ed3776259f664bf07e5e06b045dc23449e994/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/fastqc/.conda-lock/linux_amd64-bd-5cb1a2fa2f18c7c2_1.txt
    linux/arm64:
      lock_file: modules/nf-core/fastqc/.conda-lock/linux_arm64-bd-e455e32f745abe68_1.txt
