# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "custom_gtffilter"
description: Filter a gtf file to keep only regions that are located on a chromosome
  represented in a given fasta file
keywords:
  - gtf
  - fasta
  - filter
tools:
  - "gtffilter":
      description: "Filter a gtf file to keep only regions that are located on a chromosome
        represented in a given fasta file"
      tool_dev_url: "https://github.com/nf-core/modules/blob/master/modules/nf-core/custom/gtffilter/main.nf"

      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - gtf:
        type: file
        description: GTF file
        pattern: "*.{gtf}"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - fasta:
        type: file
        description: Genome fasta file
        pattern: "*.{fasta,fa}"
        ontologies: []
output:
  gtf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${prefix}.${suffix}:
          type: file
          description: Filtered GTF file
          pattern: "*.{gtf}"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
topics:
  versions:
    - versions.yml:
        type: string
        description: The name of the process
authors:
  - "@nictru"
maintainers:
  - "@nictru"
