name: "fq_subsample"
description: fq subsample outputs a subset of records from single or paired FASTQ
  files. This requires a seed (--seed) to be set in ext.args.
keywords:
  - fastq
  - fq
  - subsample
tools:
  - "fq":
      description: "fq is a library to generate and validate FASTQ file pairs."
      homepage: "https://github.com/stjude-rust-labs/fq"
      documentation: "https://github.com/stjude-rust-labs/fq"
      tool_dev_url: "https://github.com/stjude-rust-labs/fq"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: FASTQ file
        pattern: "*.{fq,fastq}{,.gz}"
output:
  - fastq:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fastq.gz":
          type: file
          description: Randomly sampled FASTQ files.
          pattern: "*_R[12].fastq.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@adamrtalbot"
maintainers:
  - "@adamrtalbot"
