name: multiqc
description: Aggregate results from bioinformatics analyses across many samples
  into a single report
keywords:
  - QC
  - bioinformatics tools
  - Beautiful stand-alone HTML report
tools:
  - multiqc:
      description: |
        MultiQC searches a given directory for analysis logs and compiles a HTML report.
        It's a general use tool, perfect for summarising the output from numerous bioinformatics tools.
      homepage: https://multiqc.info/
      documentation: https://multiqc.info/docs/
      licence:
        - "GPL-3.0-or-later"
      identifier: biotools:multiqc
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'sample1', single_end:false ]
    - multiqc_files:
        type: file
        description: |
          List of reports / files recognised by MultiQC, for example the html and zip output of FastQC
        ontologies: []
    - multiqc_config:
        type: file
        description: Optional config yml for MultiQC
        pattern: "*.{yml,yaml}"
        ontologies:
          - edam: http://edamontology.org/format_3750
    - multiqc_logo:
        type: file
        description: Optional logo file for MultiQC
        pattern: "*.{png}"
        ontologies: []
    - replace_names:
        type: file
        description: |
          Optional two-column sample renaming file. First column a set of
          patterns, second column a set of corresponding replacements. Passed via
          MultiQC's `--replace-names` option.
        pattern: "*.{tsv}"
        ontologies:
          - edam: http://edamontology.org/format_3475
    - sample_names:
        type: file
        description: |
          Optional TSV file with headers, passed to the MultiQC --sample_names
          argument.
        pattern: "*.{tsv}"
        ontologies:
          - edam: http://edamontology.org/format_3475
output:
  report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1', single_end:false ]
      - "*.html":
          type: file
          description: MultiQC report file
          pattern: ".html"
          ontologies: []
  data:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1', single_end:false ]
      - "*_data":
          type: directory
          description: MultiQC data dir
          pattern: "multiqc_data"
  plots:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1', single_end:false ]
      - "*_plots":
          type: file
          description: Plots created by MultiQC
          pattern: "*_plots"
          ontologies: []
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - multiqc:
          type: string
          description: The tool name
      - multiqc --version | sed "s/.* //g":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
maintainers:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
containers:
  conda:
    linux/amd64:
      lock_file: modules/nf-core/multiqc/.conda-lock/linux_amd64-bd-c17fb751507e9dfc_1.txt
    linux/arm64:
      lock_file: modules/nf-core/multiqc/.conda-lock/linux_arm64-bd-5c84a5000a226ab5_1.txt
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/multiqc:1.35--c17fb751507e9dfc
      build_id: bd-c17fb751507e9dfc_1
      scan_id: sc-3b1b3932f9846892_1
    linux/arm64:
      name: community.wave.seqera.io/library/multiqc:1.35--5c84a5000a226ab5
      build_id: bd-5c84a5000a226ab5_1
      scan_id: sc-0d39df41e9737bbd_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/multiqc:1.35--c680f2aea25ccec2
      build_id: bd-c680f2aea25ccec2_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/c8/c8e346f4f6080eadf1253505e6ff09ef004454fc18e8d672006fd7b222cc412e/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/multiqc:1.35--c0468833d65b2f81
      build_id: bd-c0468833d65b2f81_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/e4/e48aa28aebc881254a499b24c3e1ce77b8df1b85a5432699ed6f72eb17ac7fb5/data
