name: multiqc
description: Aggregate results from bioinformatics analyses across many samples into
  a single report
keywords:
  - QC
  - bioinformatics tools
  - Beautiful stand-alone HTML report
tools:
  - multiqc:
      description: |
        MultiQC searches a given directory for analysis logs and compiles a HTML report.
        It's a general use tool, perfect for summarising the output from numerous bioinformatics tools.
      homepage: https://multiqc.info/
      documentation: https://multiqc.info/docs/
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:multiqc
input:
  - multiqc_files:
      type: file
      description: |
        List of reports / files recognised by MultiQC, for example the html and zip output of FastQC
      ontologies: []
  - multiqc_config:
      type: file
      description: Optional config yml for MultiQC
      pattern: "*.{yml,yaml}"
      ontologies:
        - edam: http://edamontology.org/format_3750 # YAML
  - extra_multiqc_config:
      type: file
      description: Second optional config yml for MultiQC. Will override common sections
        in multiqc_config.
      pattern: "*.{yml,yaml}"
      ontologies:
        - edam: http://edamontology.org/format_3750 # YAML
  - multiqc_logo:
      type: file
      description: Optional logo file for MultiQC
      pattern: "*.{png}"
      ontologies: []
  - replace_names:
      type: file
      description: |
        Optional two-column sample renaming file. First column a set of
        patterns, second column a set of corresponding replacements. Passed via
        MultiQC's `--replace-names` option.
      pattern: "*.{tsv}"
      ontologies:
        - edam: http://edamontology.org/format_3475 # TSV
  - sample_names:
      type: file
      description: |
        Optional TSV file with headers, passed to the MultiQC --sample_names
        argument.
      pattern: "*.{tsv}"
      ontologies:
        - edam: http://edamontology.org/format_3475 # TSV
output:
  report:
    - "*.html":
        type: file
        description: MultiQC report file
        pattern: ".html"
        ontologies: []
  data:
    - "*_data":
        type: directory
        description: MultiQC data dir
        pattern: "multiqc_data"
  plots:
    - "*_plots":
        type: file
        description: Plots created by MultiQC
        pattern: "*_data"
        ontologies: []
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - multiqc:
          type: string
          description: The tool name
      - multiqc --version | sed "s/.* //g":
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
maintainers:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
