---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "custom_tx2gene"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.5
