name: star_genomegenerate
description: Create index for STAR
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - star:
      description: |
        STAR is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: https://github.com/alexdobin/STAR
      manual: https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf
      doi: 10.1093/bioinformatics/bts635
input:
  - fasta:
      type: file
      description: Fasta file of the reference genome
  - gtf:
      type: file
      description: GTF file of the reference genome

output:
  - index:
      type: directory
      description: Folder containing the star index files
      pattern: "star"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"

authors:
  - "@kevinmenden"
  - "@drpatelh"
