lint:
  actions_ci: false
  files_exist:
    - .github/workflows/ci.yml
    - conf/modules.config
  files_unchanged:
    - assets/email_template.html
    - assets/email_template.txt
    - .gitignore
  modules_config: false
  multiqc_config: false
  nextflow_config:
    - config_defaults:
        - params.ribo_database_manifest
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: "Harshil Patel, Phil Ewels, Rickard Hammar\xE9n"
  description: RNA sequencing analysis pipeline for gene/isoform quantification and
    extensive quality control.
  force: false
  is_nfcore: true
  name: rnaseq
  org: nf-core
  outdir: .
  version: 3.17.0dev
