lint:
  files_unchanged:
    - .markdownlint.yml
    - assets/email_template.html
    - assets/email_template.txt
    - bin/scrape_software_versions.py
    - lib/NfcoreTemplate.groovy
    - assets/multiqc_config.yaml
