sudo: required
language: java
jdk: openjdk8
services: docker

before_install: docker pull nfcore/rnaseq:latest

addons:
  apt:
    update: true

env:
  matrix:
    - CE=docker NXF_VER=0.30.1
    - CE=docker
    - CE=singularity NXF_VER=0.30.1
    - CE=singularity

install:
  # Install Nextflow, nf-core tools and Singularity if needed
  - "./scripts/install.sh --engine $CE"
  # Make test directories
  - mkdir ${TRAVIS_BUILD_DIR}/tests
  - cd ${TRAVIS_BUILD_DIR}/tests

script:
  # Lint the pipeline code
  - "nf-core lint ${TRAVIS_BUILD_DIR}"
  # Run, build reference genome with STAR
  - nextflow run ${TRAVIS_BUILD_DIR} -profile test,$CE
  # Run, build reference genome with HISAT2
  - nextflow run ${TRAVIS_BUILD_DIR} -profile test,$CE --aligner hisat2
