FROM nfcore/base:1.10.2

## NOTE:
##     THIS FILE ISNT REQUIRED FOR THE PIPELINE.
##     ALL DOCKER CONTAINERS ARE CURRENTLY OBTAINED FROM BIOCONTAINERS.
##     WAITING FOR NF-CORE LINT TESTS TO BE UPDATED BEFORE DELETING IT.
