# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-rnaseq-1.4dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - r-base=3.5.1
  - conda-forge::r-data.table=1.12.2
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-markdown=0.9
  - matplotlib=3.0.3        # Current 3.1.0 build incompatible with multiqc=1.7

  ## bioconda packages
  - sortmerna=2.1b # for metatranscriptomics
  - fastqc=0.11.8
  - trim-galore=0.6.2
  - star=2.6.1d             # Don't upgrade me - 2.7X indices incompatible with iGenomes.
  - rsem=1.3.2
  - salmon=0.14.0
  - hisat2=2.1.0
  - stringtie=1.3.6
  - samtools=1.9
  - picard=2.20.2
  - preseq=2.0.3
  - deeptools=3.2.1
  - gffread=0.11.4
  - qualimap=2.2.2c
  - rseqc=3.0.0
  - subread=1.6.4
  - multiqc=1.7
  - bioconductor-dupradar=1.14.0
  - bioconductor-edger=3.26.0
  - bioconductor-tximeta=1.0.3
  - bioconductor-summarizedexperiment=1.12.0
