name: picard_markduplicates
description: Locate and tag duplicate reads in a BAM file
keywords:
  - markduplicates
  - pcr
  - duplicates
  - bam
  - sam
  - cram
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: Sequence reads file, can be SAM/BAM/CRAM format
        pattern: "*.{bam,cram,sam}"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: Reference genome fasta file, required for CRAM input
        pattern: "*.{fasta,fa}"
        ontologies: []
    - fai:
        type: file
        description: Reference genome fasta index
        pattern: "*.{fai}"
        ontologies: []
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: BAM file with duplicate reads marked/removed
          pattern: "*.{bam}"
          ontologies: []
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bai":
          type: file
          description: An optional BAM index file. If desired, --CREATE_INDEX must be passed as a flag
          pattern: "*.{bai}"
          ontologies: []
  cram:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cram":
          type: file
          description: Output CRAM file
          pattern: "*.{cram}"
          ontologies: []
  metrics:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.metrics.txt":
          type: file
          description: Duplicate metrics file generated by picard
          pattern: "*.{metrics.txt}"
          ontologies: []
  versions_picard:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard MarkDuplicates --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard MarkDuplicates --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@drpatelh"
  - "@projectoriented"
  - "@ramprasadn"
maintainers:
  - "@drpatelh"
  - "@projectoriented"
  - "@ramprasadn"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/picard:3.5.0--842d4c70c98af9b4
      build_id: bd-842d4c70c98af9b4_1
      scan_id: sc-52d55041dda7855d_1
    linux/arm64:
      name: community.wave.seqera.io/library/picard:3.5.0--4f3ced346a5bb45f
      build_id: bd-4f3ced346a5bb45f_1
      scan_id: sc-8dd275c723ec21de_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/picard:3.5.0--89375ac386b71342
      build_id: bd-89375ac386b71342_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/b4/b474c6f12c0502377b95062b75ef4b7778864b1353c7fc1d5a3b1f3b3017fd2e/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/picard:3.5.0--51fe15653ca25a7c
      build_id: bd-51fe15653ca25a7c_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/35/35ed881e77f6b66f1b9204394c8909fd66da367891434a81f536704a13fad3c3/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/picard/markduplicates/.conda-lock/linux_amd64-bd-842d4c70c98af9b4_1.txt
    linux/arm64:
      lock_file: modules/nf-core/picard/markduplicates/.conda-lock/linux_arm64-bd-4f3ced346a5bb45f_1.txt
