name: ucsc_bedgraphtobigwig
description: Convert a bedGraph file to bigWig format.
keywords:
  - bedgraph
  - bigwig
  - ucsc
  - bedgraphtobigwig
  - converter
tools:
  - ucsc:
      description: Convert a bedGraph file to bigWig format.
      homepage: http://hgdownload.cse.ucsc.edu/admin/exe/
      documentation: https://genome.ucsc.edu/goldenPath/help/bigWig.html
      licence: ["varies; see http://genome.ucsc.edu/license"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bedgraph:
      type: file
      description: bedGraph file
      pattern: "*.{bedGraph}"
  - sizes:
      type: file
      description: chromosome sizes file
      pattern: "*.{sizes}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bigwig:
      type: file
      description: bigWig file
      pattern: "*.{bigWig}"
authors:
  - "@drpatelh"
maintainers:
  - "@drpatelh"
