name: samtools_stats
description: Produces comprehensive statistics from SAM/BAM/CRAM file
keywords:
  - statistics
  - counts
  - bam
  - sam
  - cram
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input:
      type: file
      description: BAM/CRAM file from alignment
      pattern: "*.{bam,cram}"
  - input_index:
      type: file
      description: BAI/CRAI file from alignment
      pattern: "*.{bai,crai}"
  - meta2:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'genome' ]
  - fasta:
      type: file
      description: Reference file the CRAM was created with (optional)
      pattern: "*.{fasta,fa}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - stats:
      type: file
      description: File containing samtools stats output
      pattern: "*.{stats}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@FriederikeHanssen"
  - "@ramprasadn"
maintainers:
  - "@drpatelh"
  - "@FriederikeHanssen"
  - "@ramprasadn"
