name: picard_collectmultiplemetrics
description: Collect multiple metrics from a BAM file
keywords:
    - alignment
    - metrics
    - statistics
    - insert
    - quality
    - bam
tools:
    - picard:
        description: |
            A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
            data and formats such as SAM/BAM/CRAM and VCF.
        homepage: https://broadinstitute.github.io/picard/
        documentation: https://broadinstitute.github.io/picard/
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: BAM file
        pattern: "*.{bam}"
    - fasta:
        type: file
        description: Genome fasta file
    - options:
        type: map
        description: |
            Groovy Map containing module options for passing command-line arguments and
            output file paths.
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - metrics:
        type: file
        description: Alignment metrics files generated by picard
        pattern: "*_{metrics}"
    - pdf:
        type: file
        description: PDF plots of metrics
        pattern: "*.{pdf}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@drpatelh"
