name: preseq_lcextrap
description: Software for predicting library complexity and genome coverage in high-throughput sequencing
keywords:
  - preseq
  - library
  - complexity
tools:
  - preseq:
      description: Software for predicting library complexity and genome coverage in high-throughput sequencing
      homepage: http://smithlabresearch.org/software/preseq/
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: ['GPL']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
  - ccurve:
      type: file
      description: File containing output of Preseq lcextrap
      pattern: "*.{ccurve.txt}"
  - log:
      type: file
      description: Log file containing stderr produced by Preseq
      pattern: "*.{log}"

authors:
  - "@drpatelh"
