name: star_genomegenerate
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::samtools=1.18
  - bioconda::htslib=1.18
  - bioconda::star=2.7.10a
  - conda-forge::gawk=5.1.0
