# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fastq_subsample_fq_salmon"
description: Subsample fastq
keywords:
  - fastq
  - subsample
  - strandedness
components:
  - fq/subsample
  - salmon/quant
  - salmon/index
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - ch_reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
  - ch_genome_fasta:
      type: file
      description: Genome fasta file
      pattern: "Path to genome sequence in fasta format"
  - ch_transcript_fasta:
      type: file
      description: Transcript fasta file
      pattern: "Path to transcript sequence in fasta format"
  - ch_gtf:
      type: file
      description: GTF features file
      pattern: "Path features in GTF format"
  - ch_index:
      type: file
      description: Salmon index files
      pattern: "Directory containing Salmon index"
  - make_index:
      type: boolean
      description: Whether to create salmon index before running salmon quant
output:
  - index:
      type: directory
      description: Directory containing salmon index
      pattern: "salmon"
  - reads:
      type: file
      description: Subsampled fastq reads.
      pattern: "*.{fq,fastq}{,.gz}"
  - results:
      type: directory
      description: Folder containing the quantification results for a specific sample
      pattern: "${prefix}"
  - json_info:
      type: file
      description: |
        File containing meta information from Salmon quant
        Which could be used to infer strandedness among other things
      pattern: "*info.json"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@robsyme"
  - "@drpatelh"
maintainers:
  - "@robsyme"
  - "@drpatelh"
