name: rseqc_innerdistance
description: Calculate inner distance between read pairs.
keywords:
  - fragment_size
  - inner_distance
tools:
  - rseqc:
      description: |
        RSeQC package provides a number of useful modules that can comprehensively evaluate
        high throughput sequence data especially RNA-seq data.
      homepage: http://rseqc.sourceforge.net/
      documentation: http://rseqc.sourceforge.net/
      doi: 10.1093/bioinformatics/bts356
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: the alignment in bam format
      pattern: "*.{bam}"
  - bed:
      type: file
      description: a bed file for the reference gene model
      pattern: "*.{bed}"
output:
  - distance:
      type: file
      description: the inner distances
      pattern: "*.inner_distance.txt"
  - freq:
      type: file
      description: frequencies of different insert sizes
      pattern: "*.inner_distance_freq.txt"
  - mean:
      type: file
      description: mean/median values of inner distances
      pattern: "*.inner_distance_mean.txt"
  - pdf:
      type: file
      description: distribution plot of inner distances
      pattern: "*.inner_distance_plot.pdf"
  - rscript:
      type: file
      description: script to reproduce the plot
      pattern: "*.inner_distance_plot.R"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@kevinmenden"
