name: rseqc_junctionannotation
description: compare detected splice junctions to reference gene model
keywords:
  - junctions
  - splicing
  - rnaseq
tools:
  - rseqc:
      description: |
        RSeQC package provides a number of useful modules that can comprehensively evaluate
        high throughput sequence data especially RNA-seq data.
      homepage: http://rseqc.sourceforge.net/
      documentation: http://rseqc.sourceforge.net/
      doi: 10.1093/bioinformatics/bts356
      licence: ["GPL-3.0-or-later"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: the alignment in bam format
      pattern: "*.{bam}"
  - bed:
      type: file
      description: a bed file for the reference gene model
      pattern: "*.{bed}"
output:
  - bed:
      type: file
      description: bed file of annotated junctions
      pattern: "*.junction.bed"
  - interact_bed:
      type: file
      description: Interact bed file
      pattern: "*.Interact.bed"
  - xls:
      type: file
      description: xls file with junction information
      pattern: "*.xls"
  - pdf:
      type: file
      description: junction plot
      pattern: "*.junction.pdf"
  - events_pdf:
      type: file
      description: events plot
      pattern: "*.events.pdf"
  - rscript:
      type: file
      description: Rscript to reproduce the plots
      pattern: "*.r"
  - log:
      type: file
      description: Log file of execution
      pattern: "*.junction_annotation.log"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@kevinmenden"
