# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_dedup_stats_samtools_umicollapse"
description: umicollapse, index BAM file and run samtools stats, flagstat and idxstats
keywords:
  - umi
  - dedup
  - index
  - bam
  - sam
  - cram
components:
  - umicollapse
  - samtools/index
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat
  - bam_stats_samtools
input:
  - ch_bam_bai:
      description: |
        input BAM file
        Structure: [ val(meta), path(bam), path(bai) ]
output:
  - bam:
      description: |
        Umi deduplicated BAM/SAM file
        Structure: [ val(meta), path(bam) ]
  - bai:
      description: |
        Umi deduplicated BAM/SAM samtools index
        Structure: [ val(meta), path(bai) ]
  - csi:
      description: |
        CSI samtools index
        Structure: [ val(meta), path(csi) ]
  - dedupstats:
      description: |
        File containing umicollapse deduplication stats
        Structure: [ val(meta), path(stats) ]
  - stats:
      description: |
        File containing samtools stats output
        Structure: [ val(meta), path(stats) ]
  - flagstat:
      description: |
        File containing samtools flagstat output
        Structure: [ val(meta), path(flagstat) ]
  - idxstats:
      description: |
        File containing samtools idxstats output
        Structure: [ val(meta), path(idxstats) ]
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@MatthiasZepper"
maintainers:
  - "@MatthiasZepper"
