# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "concatenate_fasta"
description: Concatenate FASTA files into a single FASTA file, each followed by a newline.
keywords:
  - fasta
  - concatenate
tools: []
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information, e.g. `[ id:'rrna_refs' ]`
    - fastas:
        type: file
        description: FASTA files to concatenate, in the given order
        pattern: "*.{fa,fasta,fna}"
output:
  fasta:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - rrna_combined_dna.fasta:
          type: file
          description: Concatenated FASTA file
          pattern: "*.fasta"
authors:
  - "@pinin4fjords"
maintainers:
  - "@pinin4fjords"
