name: fastp
description: Perform adapter/quality trimming on sequencing reads
keywords:
  - trimming
  - quality control
  - fastq
tools:
  - fastp:
      description: |
        A tool designed to provide fast all-in-one preprocessing for FastQ files. This tool is developed in C++ with multithreading supported to afford high performance.
      documentation: https://github.com/OpenGene/fastp
      doi: 10.1093/bioinformatics/bty560
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information. Use 'single_end: true' to specify single ended or interleaved FASTQs. Use 'single_end: false' for paired-end reads.
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively. If you wish to run interleaved paired-end data,  supply as single-end data
        but with `--interleaved_in` in your `modules.conf`'s `ext.args` for the module.
  - adapter_fasta:
      type: file
      description: File in FASTA format containing possible adapters to remove.
      pattern: "*.{fasta,fna,fas,fa}"
  - save_trimmed_fail:
      type: boolean
      description: Specify true to save files that failed to pass trimming thresholds ending in `*.fail.fastq.gz`
  - save_merged:
      type: boolean
      description: Specify true to save all merged reads to the a file ending in `*.merged.fastq.gz`
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: The trimmed/modified/unmerged fastq reads
      pattern: "*fastp.fastq.gz"
  - json:
      type: file
      description: Results in JSON format
      pattern: "*.json"
  - html:
      type: file
      description: Results in HTML format
      pattern: "*.html"
  - log:
      type: file
      description: fastq log file
      pattern: "*.log"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - reads_fail:
      type: file
      description: Reads the failed the preprocessing
      pattern: "*fail.fastq.gz"
  - reads_merged:
      type: file
      description: Reads that were successfully merged
      pattern: "*.{merged.fastq.gz}"
authors:
  - "@drpatelh"
  - "@kevinmenden"
maintainers:
  - "@drpatelh"
  - "@kevinmenden"
