name: "umicollapse"
description: Deduplicate reads based on the mapping co-ordinate and the UMI attached
  to the read.
keywords:
  - umicollapse
  - deduplication
  - genomics
tools:
  - "umicollapse":
      description: "UMICollapse contains tools for dealing with Unique Molecular Identifiers
        (UMIs)/Random Molecular Tags (RMTs)."
      homepage: "https://github.com/Daniel-Liu-c0deb0t/UMICollapse"
      documentation: "https://github.com/Daniel-Liu-c0deb0t/UMICollapse"
      tool_dev_url: "https://github.com/siddharthab/UMICollapse"
      doi: "10.7717/peerj.8275"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: Input bam file
        pattern: "*.bam"
    - bai:
        type: file
        description: |
          BAM index files corresponding to the input BAM file. Optionally can be skipped using [] when using FastQ input.
        pattern: "*.{bai}"
  - - mode:
        type: string
        description: |
          Selects the mode of Umicollapse - either fastq or bam need to be provided.
        pattern: "{fastq,bam}"
output:
  - bam:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: BAM file with deduplicated UMIs.
          pattern: "*.{bam}"
  - fastq:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
      - "*dedup*fastq.gz":
          type: file
          description: FASTQ file with deduplicated UMIs.
          pattern: "*dedup*fastq.gz"
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
      - "*_UMICollapse.log":
          type: file
          description: A log file with the deduplication statistics.
          pattern: "*_{UMICollapse.log}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@CharlotteAnne"
  - "@chris-cheshire"
maintainers:
  - "@CharlotteAnne"
  - "@chris-cheshire"
  - "@apeltzer"
  - "@siddharthab"
  - "@MatthiasZepper"
