name: star_align
description: Align reads to a reference genome using STAR
keywords:
  - align
  - fasta
  - genome
  - reference
tools:
  - star:
      description: |
        STAR is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: https://github.com/alexdobin/STAR
      manual: https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf
      doi: 10.1093/bioinformatics/bts635
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
  - index:
      type: directory
      description: STAR genome index
      pattern: "star"
output:
  - bam:
      type: file
      description: Output BAM file containing read alignments
      pattern: "*.{bam}"
  - log_final:
      type: file
      description: STAR final log file
      pattern: "*Log.final.out"
  - log_out:
      type: file
      description: STAR lot out file
      pattern: "*Log.out"
  - log_progress:
      type: file
      description: STAR log progress file
      pattern: "*Log.progress.out"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bam_sorted:
      type: file
      description: Sorted BAM file of read alignments (optional)
      pattern: "*sortedByCoord.out.bam"
  - bam_transcript:
      type: file
      description: Output BAM file of transcriptome alignment (optional)
      pattern: "*toTranscriptome.out.bam"
  - bam_unsorted:
      type: file
      description: Unsorted BAM file of read alignments (optional)
      pattern: "*Aligned.unsort.out.bam"
  - fastq:
      type: file
      description: Unmapped FastQ files (optional)
      pattern: "*fastq.gz"
  - tab:
      type: file
      description: STAR output tab file(s) (optional)
      pattern: "*.tab"
  - junction:
      type: file
      description: STAR chimeric junction output file (optional)
      pattern: "*.out.junction"

authors:
  - "@kevinmenden"
  - "@drpatelh"
  - "@praveenraj2018"
