name: sortmerna
description: Local sequence alignment tool for filtering, mapping and clustering.
keywords:
  - filtering
  - mapping
  - clustering
  - rRNA
  - ribosomal RNA
tools:
  - SortMeRNA:
      description: The core algorithm is based on approximate seeds and allows for sensitive
        analysis of NGS reads. The main application of SortMeRNA is filtering rRNA from
        metatranscriptomic data. SortMeRNA takes as input files of reads (fasta, fastq,
        fasta.gz, fastq.gz) and one or multiple rRNA database file(s), and sorts apart
        aligned and rejected reads into two files. Additional applications include clustering
        and taxonomy assignation available through QIIME v1.9.1. SortMeRNA works with
        Illumina, Ion Torrent and PacBio data, and can produce SAM and BLAST-like alignments.
      homepage: https://hpc.nih.gov/apps/sortmeRNA.html
      documentation: https://github.com/biocore/sortmerna/wiki/
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:sortmerna
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test' ]
    - fastas:
        type: file
        description: |
          Path to reference file(s)
  - - meta3:
        type: map
        description: |
          Groovy Map containing index information
          e.g. [ id:'test' ]
    - index:
        type: directory
        description: |
          Path to index directory of a previous sortmerna run
output:
  - reads:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ], or reference information from an
            indexing-only run
      - "*non_rRNA.fastq.gz":
          type: file
          description: The filtered fastq reads
          pattern: "*fastq.gz"
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ], or reference information from an
            indexing-only run
      - "*.log":
          type: file
          description: SortMeRNA log file
          pattern: "*sortmerna.log"
  - index:
      - meta2:
          type: map
          description: |
            Groovy Map containing reference information
            e.g. [ id:'test' ]
      - idx:
          type: directory
          description: |
            Path to index directory generated by sortmern
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@mashehu"
maintainers:
  - "@drpatelh"
  - "@mashehu"
