name: rsem_calculateexpression
description: Calculate expression with RSEM
keywords:
  - rsem
  - expression
  - quantification
tools:
  - rseqc:
      description: |
        RSEM: accurate transcript quantification from RNA-Seq data with or without a reference genome
      homepage: https://github.com/deweylab/RSEM
      documentation: https://github.com/deweylab/RSEM
      doi: 10.1186/1471-2105-12-323
      licence: ["GPL-3.0-or-later"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: Input reads for quantification
      pattern: "*.fastq.gz"
  - index:
      type: file
      description: RSEM index
      pattern: "rsem/*"
output:
  - counts_gene:
      type: file
      description: Expression counts on gene level
      pattern: "*.genes.results"
  - counts_transctips:
      type: file
      description: Expression counts on transcript level
      pattern: "*.isoforms.results"
  - stat:
      type: file
      description: RSEM statistics
      pattern: "*.stat"
  - logs:
      type: file
      description: RSEM logs
      pattern: "*.log"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bam_star:
      type: file
      description: BAM file generated by STAR (optional)
      pattern: "*.STAR.genome.bam"
  - bam_genome:
      type: file
      description: Genome BAM file (optional)
      pattern: "*.genome.bam"
  - bam_transcript:
      type: file
      description: Transcript BAM file (optional)
      pattern: "*.transcript.bam"
authors:
  - "@drpatelh"
  - "@kevinmenden"
