---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  # Fast mode dependencies
  - bioconda::subread=2.0.1
  - conda-forge::python=3.9
  - conda-forge::matplotlib=3.5.2
  - conda-forge::numpy=1.21.5
  - conda-forge::pandas=1.5.3
  - conda-forge::scipy=1.10.1
  # R for plotting (minimal R environment)
  - conda-forge::r-base=4.1.3
  - conda-forge::r-kernsmooth=2.23_20