name: stringtie_stringtie
description: Transcript assembly and quantification for RNA-Se
keywords:
  - transcript
  - assembly
  - quantification
  - gtf
tools:
  - stringtie2:
      description: |
        Transcript assembly and quantification for RNA-Seq
      homepage: https://ccb.jhu.edu/software/stringtie/index.shtml
      documentation: https://ccb.jhu.edu/software/stringtie/index.shtml?t=manual
      licence:
        - "MIT"
      identifier: biotools:stringtie
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', strandedness:'forward' ]
    - srbam:
        type: file
        description: |
          Sorted and indexed bam file from short-read alignment.
        pattern: ".bam"
        ontologies: []
    - lrbam:
        type: file
        description: |
          Sorted and indexed bam file from long-read alignment.
        pattern: ".bam"
        ontologies: []
  - mode:
      type: string
      description: |
        StringTie mode (long-read-assembly, mix-read-assembly, expression-estimation, nascent-aware-assembly).
      enum:
        - long-read-assembly
        - mix-read-assembly
        - expression-estimation
        - nascent-aware-assembly
  - annotation_gtf:
      type: file
      description: |
        Annotation gtf file (optional).
      pattern: ".gtf"
      ontologies: []
output:
  transcript_gtf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', strandedness:'forward' ]
      - ${prefix}.transcripts.gtf:
          type: file
          description: |
            Output assembly (transcriptome)
          pattern: ".gtf"
          ontologies: []
  abundance:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', strandedness:'forward' ]
      - ${prefix}.gene.abundance.txt:
          type: file
          description: |
            Abundance for non-redundand set of transcripts
          pattern: ".txt"
          ontologies: []
  coverage_gtf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', strandedness:'forward' ]
      - ${prefix}.coverage.gtf:
          type: file
          description: |
            Coverage for the sample
          pattern: ".gtf"
          ontologies: []
  ballgown:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', strandedness:'forward' ]
      - ${prefix}.ballgown/*.ctab:
          type: file
          description: |
            Ballgown output for the sample
          pattern: ".ctab"
          ontologies: []
  versions_stringtie:
    - - ${task.process}:
          type: string
          description: The name of the process
      - stringtie:
          type: string
          description: The name of the tool
      - stringtie --version:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - stringtie:
          type: string
          description: The name of the tool
      - stringtie --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@drpatelh"
  - "@khersameesh24"
maintainers:
  - "@drpatelh"
  - "@khersameesh24"
