name: hisat2_extractsplicesites
description: Extracts splicing sites from a gtf files
keywords:
    - splicing
    - gtf
    - genome
    - reference

tools:
  - hisat2:
      description: HISAT2 is a fast and sensitive alignment program for mapping next-generation sequencing reads (both DNA and RNA) to a population of human genomes as well as to a single reference genome.
      homepage: https://daehwankimlab.github.io/hisat2/
      documentation: https://daehwankimlab.github.io/hisat2/manual/
      doi: "10.1038/s41587-019-0201-4"
      licence: ['MIT']

input:
  - gtf:
      type: file
      description: Reference gtf annotation file
      pattern: "*.{gtf}"

output:
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
  - splicesites:
      type: file
      description: Splices sites in gtf file
      pattern: "*.{splice_sites.txt}"

authors:
  - "@ntoda03"
