name: rseqc_junctionsaturation
description: compare detected splice junctions to reference gene model
keywords:
  - junctions
  - splicing
  - rnaseq
tools:
  - rseqc:
      description: |
        RSeQC package provides a number of useful modules that can comprehensively evaluate
        high throughput sequence data especially RNA-seq data.
      homepage: http://rseqc.sourceforge.net/
      documentation: http://rseqc.sourceforge.net/
      doi: 10.1093/bioinformatics/bts356
      licence: ["GPL-3.0-or-later"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: the alignment in bam format
      pattern: "*.{bam}"
  - bed:
      type: file
      description: a bed file for the reference gene model
      pattern: "*.{bed}"
output:
  - pdf:
      type: file
      description: Junction saturation report
      pattern: "*.pdf"
  - rscript:
      type: file
      description: Junction saturation R-script
      pattern: "*.r"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@kevinmenden"
