name: salmon_index
description: Create index for salmon
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - salmon:
      description: |
        Salmon is a tool for wicked-fast transcript quantification from RNA-seq data
      homepage: https://salmon.readthedocs.io/en/latest/salmon.html
      manual: https://salmon.readthedocs.io/en/latest/salmon.html
      doi: 10.1038/nmeth.4197
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:salmon
input:
  - - genome_fasta:
        type: file
        description: Fasta file of the reference genome
  - - transcript_fasta:
        type: file
        description: Fasta file of the reference transcriptome
output:
  - index:
      - salmon:
          type: directory
          description: Folder containing the star index files
          pattern: "salmon"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@kevinmenden"
  - "@drpatelh"
maintainers:
  - "@kevinmenden"
  - "@drpatelh"
