name: rseqc_tin
description: Calculate TIN (transcript integrity number) from RNA-seq reads
keywords:
  - rnaseq
  - transcript
  - integrity
tools:
  - rseqc:
      description: |
        RSeQC package provides a number of useful modules that can comprehensively evaluate
        high throughput sequence data especially RNA-seq data.
      homepage: http://rseqc.sourceforge.net/
      documentation: http://rseqc.sourceforge.net/
      doi: 10.1093/bioinformatics/bts356
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:rseqc
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Input BAM file
        pattern: "*.{bam}"
    - bai:
        type: file
        description: Index for input BAM file
        pattern: "*.{bai}"
  - - bed:
        type: file
        description: BED file containing the reference gene model
        pattern: "*.{bed}"
output:
  - txt:
      - meta:
          type: file
          description: TXT file containing tin.py results summary
          pattern: "*.txt"
      - "*.txt":
          type: file
          description: TXT file containing tin.py results summary
          pattern: "*.txt"
  - xls:
      - meta:
          type: file
          description: XLS file containing tin.py results
          pattern: "*.xls"
      - "*.xls":
          type: file
          description: XLS file containing tin.py results
          pattern: "*.xls"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@drpatelh"
maintainers:
  - "@drpatelh"
