name: gffread
description: Validate, filter, convert and perform various other operations on GFF files
keywords:
  - gff
  - conversion
  - validation
tools:
  - gffread:
      description: GFF/GTF utility providing format conversions, region filtering, FASTA sequence extraction and more.
      homepage: http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread
      documentation: http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread
      tool_dev_url: https://github.com/gpertea/gffread
      doi: 10.12688/f1000research.23297.1
      licence: ["MIT"]
input:
  - gff:
      type: file
      description: A reference file in either the GFF3, GFF2 or GTF format.
      pattern: "*.{gff, gtf}"
output:
  - gtf:
      type: file
      description: GTF file resulting from the conversion of the GFF input file if '-T' argument is present
      pattern: "*.{gtf}"
  - gffread_gff:
      type: file
      description: GFF3 file resulting from the conversion of the GFF input file if '-T' argument is absent
      pattern: "*.{gff3}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@edmundmiller"
maintainers:
  - "@edmundmiller"
