name: ucsc_bedclip
description: Remove lines from bed file that refer to off-chromosome locations.
keywords:
  - bed
  - genomics
  - ucsc
tools:
  - ucsc:
      description: Remove lines from bed file that refer to off-chromosome locations.
      homepage: http://hgdownload.cse.ucsc.edu/admin/exe/
      licence: ["varies; see http://genome.ucsc.edu/license"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bedgraph:
      type: file
      description: bedGraph file
      pattern: "*.{bedgraph}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bedgraph:
      type: file
      description: bedGraph file
      pattern: "*.{bedgraph}"
authors:
  - "@drpatelh"
maintainers:
  - "@drpatelh"
