name: bbmap_bbsplit
description: Split sequencing reads by mapping them to multiple references simultaneously
keywords:
  - align
  - map
  - fastq
  - genome
  - reference
tools:
  - bbmap:
      description: BBMap is a short read aligner, as well as various other bioinformatic
        tools.
      homepage: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/
      documentation: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/
      licence: ["UC-LBL license (see package)"]
      identifier: biotools:bbmap
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies: []
  - index:
      type: directory
      description: Directory to place generated index
      pattern: "*"
  - primary_ref:
      type: file
      description: Path to the primary reference
      pattern: "*"
      ontologies: []
  - - other_ref_names:
        type: list
        description: List of other reference ids apart from the primary
    - other_ref_paths:
        type: list
        description: Path to other references paths corresponding to "other_ref_names"
  - only_build_index:
      type: string
      description: true = only build index; false = mapping
output:
  index:
    - bbsplit_index:
        type: directory
        description: Directory with index files
        pattern: "bbsplit_index"
  primary_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*primary*fastq.gz":
          type: file
          description: Output reads that map to the primary reference
          pattern: "*primary*fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  all_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*fastq.gz":
          type: file
          description: All reads mapping to any of the references
          pattern: "*fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  stats:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*txt":
          type: file
          description: Tab-delimited text file containing mapping statistics
          pattern: "*.txt"
          ontologies: []
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.log":
          type: file
          description: Log file
          pattern: "*.log"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@joseespinosa"
  - "@drpatelh"
  - "@pinin4fjords"
maintainers:
  - "@joseespinosa"
  - "@drpatelh"
  - "@pinin4fjords"
