# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bam_rseqc
description: Subworkflow to run multiple commands in the RSeqC package
keywords:
  - rnaseq
  - experiment
  - inferexperiment
  - bamstat
  - innerdistance
  - junctionannotation
  - junctionsaturation
  - readdistribution
  - readduplication
  - tin
components:
  - rseqc
  - rseqc/tin
  - rseqc/readduplication
  - rseqc/readdistribution
  - rseqc/junctionsaturation
  - rseqc/junctionannotation
  - rseqc/innerdistance
  - rseqc/inferexperiment
  - rseqc/bamstat
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file to calculate statistics
      pattern: "*.{bam}"
  - bai:
      type: file
      description: Index for input BAM file
      pattern: "*.{bai}"
  - bed:
      type: file
      description: BED file for the reference gene model
      pattern: "*.{bed}"
  - rseqc_modules:
      type: list
      description: |
        List of rseqc modules to run
        e.g. [ 'bam_stat', 'infer_experiment' ]
output:
  - bamstat_txt:
      type: file
      description: bam statistics report
      pattern: "*.bam_stat.txt"
  - innerdistance_all:
      type: file
      description: All the output files from RSEQC_INNERDISTANCE
      pattern: "*.{txt,pdf,R}"
  - innerdistance_distance:
      type: file
      description: the inner distances
      pattern: "*.inner_distance.txt"
  - innerdistance_freq:
      type: file
      description: frequencies of different insert sizes
      pattern: "*.inner_distance_freq.txt"
  - innerdistance_mean:
      type: file
      description: mean/median values of inner distances
      pattern: "*.inner_distance_mean.txt"
  - innerdistance_pdf:
      type: file
      description: distribution plot of inner distances
      pattern: "*.inner_distance_plot.pdf"
  - innerdistance_rscript:
      type: file
      description: script to reproduce the plot
      pattern: "*.inner_distance_plot.R"
  - inferexperiment_txt:
      type: file
      description: infer_experiment results report
      pattern: "*.infer_experiment.txt"
  - junctionannotation_all:
      type: file
      description: All the output files from RSEQC_JUNCTIONANNOTATION
      pattern: "*.{bed,xls,pdf,R,log}"
  - junctionannotation_bed:
      type: file
      description: bed file of annotated junctions
      pattern: "*.junction.bed"
  - junctionannotation_interact_bed:
      type: file
      description: Interact bed file
      pattern: "*.Interact.bed"
  - junctionannotation_xls:
      type: file
      description: xls file with junction information
      pattern: "*.xls"
  - junctionannotation_pdf:
      type: file
      description: junction plot
      pattern: "*.junction.pdf"
  - junctionannotation_events_pdf:
      type: file
      description: events plot
      pattern: "*.events.pdf"
  - junctionannotation_rscript:
      type: file
      description: Rscript to reproduce the plots
      pattern: "*.r"
  - junctionannotation_log:
      type: file
      description: Log file generated by tool
      pattern: "*.log"
  - junctionsaturation_all:
      type: file
      description: All the output files from RSEQC_JUNCTIONSATURATION
      pattern: "*.{pdf,R}"
  - junctionsaturation_pdf:
      type: file
      description: Junction saturation report
      pattern: "*.pdf"
  - junctionsaturation_rscript:
      type: file
      description: Junction saturation R-script
      pattern: "*.r"
  - readdistribution_txt:
      type: file
      description: the read distribution report
      pattern: "*.read_distribution.txt"
  - readduplication_all:
      type: file
      description: All the output files from RSEQC_READDUPLICATION
      pattern: "*.{xls,pdf,R}"
  - readduplication_seq_xls:
      type: file
      description: Read duplication rate determined from mapping position of read
      pattern: "*seq.DupRate.xls"
  - readduplication_pos_xls:
      type: file
      description: Read duplication rate determined from sequence of read
      pattern: "*pos.DupRate.xls"
  - readduplication_pdf:
      type: file
      description: plot of duplication rate
      pattern: "*.pdf"
  - readduplication_rscript:
      type: file
      description: script to reproduce the plot
      pattern: "*.R"
  - tin_txt:
      type: file
      description: TXT file containing tin.py results summary
      pattern: "*.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@kevinmenden"
maintainers:
  - "@drpatelh"
  - "@kevinmenden"
