name: bedtools_sort
description: Sorts a feature file by chromosome and other criteria.
keywords:
  - bed
  - sort
  - bedtools
  - chromosome
tools:
  - bedtools:
      description: |
        A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
      documentation: https://bedtools.readthedocs.io/en/latest/content/tools/sort.html
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - intervals:
      type: file
      description: BED/BEDGRAPH
      pattern: "*.{bed|bedGraph}"
  - genome_file:
      type: file
      description: |
        Optional reference genome 2 column file that defines the expected chromosome order.
      pattern: "*.{fai,txt,chromsizes}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - sorted:
      type: file
      description: Sorted output file
      pattern: "*.${extension}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@edmundmiller"
  - "@sruthipsuresh"
  - "@drpatelh"
  - "@chris-cheshire"
  - "@adamrtalbot"
maintainers:
  - "@edmundmiller"
  - "@sruthipsuresh"
  - "@drpatelh"
  - "@chris-cheshire"
  - "@adamrtalbot"
