name: small-sized tests on cloud providers
run-name: Submitting workflow to all cloud providers using small sized data
on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to run test"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - aws
          - azure
          - gcp
jobs:
  run-small-tests-on-aws:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'aws' }}
    runs-on: ubuntu-latest
    steps:
      - uses: seqeralabs/action-seqera-launch@1bcb34fe032e7eeda8861d85490e890cf5aa6c76 # v1.0.0-rc.1
        with:
          workspace-id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access-token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute-env: ${{ secrets.TOWER_CE_AWS_CPU }}
          work-dir: "${{ secrets.TOWER_BUCKET_AWS }}/work/rnaseq/work-${{ github.sha }}"
          run-name: "aws_rnaseq_small"
          revision: ${{ github.sha }}
          profiles: test
          parameters: |
            {
                "outdir": "${{ secrets.TOWER_BUCKET_AWS }}/rnaseq/results-test-${{ github.sha }}/"
            }
          wait: running

  run-small-tests-on-azure:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'azure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: seqeralabs/action-seqera-launch@1bcb34fe032e7eeda8861d85490e890cf5aa6c76 # v1.0.0-rc.1
        with:
          workspace-id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access-token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute-env: ${{ secrets.TOWER_CE_AZURE_CPU }}
          work-dir: "${{ secrets.TOWER_BUCKET_AZURE }}/work/rnaseq/work-${{ github.sha }}"
          run-name: "azure_rnaseq_small"
          revision: ${{ github.sha }}
          profiles: test
          parameters: |
            {
                "outdir": "${{ secrets.TOWER_BUCKET_AZURE }}/rnaseq/results-test-${{ github.sha }}/"
            }
          wait: running

  run-small-tests-on-gcp:
    if: ${{ github.event.inputs.platform == 'gcp' }}
    runs-on: ubuntu-latest
    steps:
      - uses: seqeralabs/action-seqera-launch@1bcb34fe032e7eeda8861d85490e890cf5aa6c76 # v1.0.0-rc.1
        with:
          workspace-id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access-token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute-env: ${{ secrets.TOWER_CE_GCP_CPU }}
          work-dir: "${{ secrets.TOWER_BUCKET_GCP }}/work/rnaseq/work-${{ github.sha }}"
          run-name: "gcp_rnaseq_small"
          revision: ${{ github.sha }}
          profiles: test
          parameters: |
            {
                "outdir": "${{ secrets.TOWER_BUCKET_GCP }}/rnaseq/results-test-${{ github.sha }}/"
            }
          wait: running
