name: full-sized tests on cloud providers
run-name: Submitting workflow to all cloud providers using full sized data
on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to run test"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - aws
          - azure
          - gcp
  pull_request_review:
    types: [submitted]
jobs:
  run-full-tests-on-aws:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'aws' || !github.event.inputs || (github.repository == 'nf-core/rnaseq' && github.event.review.state == 'approved' && (github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'main')) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aligner: ["star_salmon", "star_rsem"]
    steps:
      - name: Launch workflow via Seqera Platform
        uses: seqeralabs/action-tower-launch@refactor-javascript
        with:
          workspace_id: ${{ vars.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ vars.TOWER_COMPUTE_ENV_CPU }}
          workdir: "${{ secrets.TOWER_BUCKET_AWS }}/work/rnaseq/work-${{ github.sha }}"
          run_name: "aws_rnaseq_full_${{ matrix.aligner }}"
          revision: ${{ github.sha }}
          profiles: test_full_aws
          parameters: |
            {
                "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
                "aligner": "${{ matrix.aligner }}",
                "outdir": "${{ secrets.TOWER_BUCKET_AWS }}/rnaseq/results-${{ github.sha }}/aligner_${{ matrix.aligner }}/"
            }
      - uses: actions/upload-artifact@v4
        with:
          name: Seqera Platform debug log file (${{ matrix.aligner }})
          path: |
            seqera_platform_action_*.log
            seqera_platform_action_*.json

  run-full-tests-on-azure:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'azure' || !github.event.inputs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aligner: ["star_salmon", "star_rsem"]
    steps:
      - uses: seqeralabs/action-tower-launch@refactor-javascript
        with:
          workspace_id: ${{ vars.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ vars.TOWER_COMPUTE_ENV_CPU }}
          workdir: "${{ secrets.TOWER_BUCKET_AZURE }}/work/rnaseq/work-${{ github.sha }}"
          run_name: "azure_rnaseq_full_${{ matrix.aligner }}"
          revision: ${{ github.sha }}
          profiles: test_full_azure
          parameters: |
            {
                "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
                "aligner": "${{ matrix.aligner }}",
                "outdir": "${{ secrets.TOWER_BUCKET_AZURE }}/rnaseq/results-${{ github.sha }}/aligner_${{ matrix.aligner }}/",
                "igenomes_base": "${{ secrets.TOWER_IGENOMES_BASE_AZURE }}"
            }
      - uses: actions/upload-artifact@v4
        with:
          name: Seqera Platform debug log file (${{ matrix.aligner }})
          path: |
            seqera_platform_action_*.log
            seqera_platform_action_*.json

  run-full-tests-on-gcp:
    if: ${{ github.event.inputs.platform == 'gcp' || !github.event.inputs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aligner: ["star_salmon", "star_rsem"]
    steps:
      - uses: seqeralabs/action-tower-launch@refactor-javascript
        with:
          workspace_id: ${{ vars.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ vars.TOWER_COMPUTE_ENV_CPU }}
          workdir: "${{ secrets.TOWER_BUCKET_GCP }}/work/rnaseq/work-${{ github.sha }}"
          run_name: "gcp_rnaseq_full_${{ matrix.aligner }}"
          revision: ${{ github.sha }}
          profiles: test_full_gcp
          parameters: |
            {
                "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
                "aligner": "${{ matrix.aligner }}",
                "outdir": "${{ secrets.TOWER_BUCKET_GCP }}/rnaseq/results-${{ github.sha }}/aligner_${{ matrix.aligner }}/"
            }
      - uses: actions/upload-artifact@v4
        with:
          name: Seqera Platform debug log file (${{ matrix.aligner }})
          path: |
            seqera_platform_action_*.log
            seqera_platform_action_*.json
