name: Container Configs

on:
  # FIXME Remove these and only run on release or PRs to main
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]
  release:
    types: [published]
  # TODO workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      matrix:
        container_type: ['docker', 'singularity'] # TODO , "singularity_oras"]
        architecture: ['amd64', 'arm64']
    steps:
      # TODO
      # - uses: earthly/actions/setup-earthly@v1
      #   with:
      #     version: v0.8.13
      - uses: actions/checkout@v2
      - uses: nf-core/setup-nextflow@v2
        with:
          version: "25.01.0-edge"
      - name: Snapshot containers
        run: |
          if [ "${{ matrix.architecture }}" == "arm64" ]; then
            profile="wave,${{ matrix.container_type }},arm"
          else
            profile="wave,${{ matrix.container_type }}"
          fi
          nextflow inspect . -profile $profile -format config > conf/containers/containers_${{ matrix.container_type }}_${{ matrix.architecture }}.config

