name: Container Configs

on:
  # FIXME Remove these and only run on release or PRs to main or TEMPLATE updates
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]
  release:
    types: [published]
  # TODO workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      matrix:
        container_type: ['docker', 'singularity'] # TODO , "singularity_oras"]
        architecture: ['amd64', 'arm64']
    steps:
      # TODO
      # - uses: earthly/actions/setup-earthly@v1
      #   with:
      #     version: v0.8.13
      # Use the @nf-core-bot token to check out so we can push later
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.nf_core_bot_auth_token }}
          ref: ${{ github.head_ref }}
      - uses: nf-core/setup-nextflow@v2
        with:
          version: "25.01.0-edge"
      - name: Snapshot containers
        run: |
          if [ "${{ matrix.architecture }}" == "arm64" ]; then
            profile="wave,${{ matrix.container_type }},arm"
          else
            profile="wave,${{ matrix.container_type }}"
          fi
          nextflow inspect . -profile $profile -format config > conf/containers/containers_${{ matrix.container_type }}_${{ matrix.architecture }}.config
      - name: Commit & push changes
        id: commit-and-push
        run: |
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git config push.default upstream
          git add conf/containers/
          git status
          git commit -m "[automated] Update container configs"
          git push

