name: Nextflow strict syntax lint
on:
  pull_request:
  push:
    branches: [master, dev]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@b4ec1bc7c16a94435159de94a05253542fddf6ef # v3

      - name: Nextflow strict syntax lint
        run: nextflow lint -o concise -exclude nf-test.config .
