name: qualimap_rnaseq
description: Evaluate alignment data
keywords:
  - quality control
  - qc
  - rnaseq
tools:
  - qualimap:
      description: |
        Qualimap 2 is a platform-independent application written in
        Java and R that provides both a Graphical User Interface and
        a command-line interface to facilitate the quality control of
        alignment sequencing data and its derivatives like feature counts.
      homepage: http://qualimap.bioinfo.cipf.es/
      documentation: http://qualimap.conesalab.org/doc_html/index.html
      doi: 10.1093/bioinformatics/bts503
      licence: ["GPL-2.0-only"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - meta2:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'test' ]
  - gtf:
      type: file
      description: GTF file of the reference genome
      pattern: "*.{gtf}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - results:
      type: directory
      description: Qualimap results dir
      pattern: "*/*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@FriederikeHanssen"
maintainers:
  - "@FriederikeHanssen"
