name: untar
description: Extract files.
keywords:
  - untar
  - uncompress
tools:
  - untar:
      description: |
        Extract tar.gz files.
      documentation: https://www.gnu.org/software/tar/manual/
      licence: ["GPL-3.0-or-later"]
input:
  - archive:
      type: file
      description: File to be untar
      pattern: "*.{tar}.{gz}"
output:
  - untar:
      type: file
      description:
      pattern: "*.*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@joseespinosa"
  - "@drpatelh"
